local plug = vim.fn['plug#']

vim.call('plug#begin', '~/.config/nvim/plugged')
plug('nvim-lua/plenary.nvim')
plug('nvim-telescope/telescope.nvim')
plug('morhetz/gruvbox')
plug('neoclide/coc.nvim', { branch = 'release' })
plug('nvim-treesitter/nvim-treesitter', { ['do'] = ':TSUpdate' })
plug('nvim-lualine/lualine.nvim')
plug('nvim-tree/nvim-web-devicons')
plug('airblade/vim-gitgutter')
plug('pangloss/vim-javascript')
plug('stevearc/oil.nvim')
plug('fatih/vim-go', { ['do'] = ':GoUpdateBinaries' })
vim.call('plug#end')
